---
- name: Install Loadbalancer Server
  hosts: lan_lb
  become: true
  vars:
    list_open_services: ["http", "https"]
    list_open_ports: ["9000"]
  roles:
    - role: firewalld
    - role: loadbalancer
...
