---
- name: Install Nextcloud
  hosts: lan_nc
  become: true
  vars:
    list_open_services: ["http", "https"]
    openssl_dhparam:
    webserver:
      name: "nginx" # or httpd
      user: "nginx" # or apache, group's name is the same
      php_socket: "/run/php-fpm/php-fpm.sock"
    #      php_socket: "/run/php-fpm/www.sock"
  roles:
    - role: "{{ webserver.name | default(httpd) }}"
      tags: "{{ webserver.name | default(httpd) }}"
    - role: firewalld
    - role: php
    - role: nextcloud
...
