---
- name: reboot
  reboot:
    reboot_timeout: 60
- name: httpd_restart
  service:
    name: httpd
    state: restarted
- name: php_restart
  service:
    name: php-fpm
    state: restarted
- name: nginx_restart
  service:
    name: nginx
    state: restarted
- name: change_libphp_owner
  file:
    path: "/var/lib/php/"
    state: directory
    owner: nginx
    group: nginx
    recurse: yes
  when: webserver.name == "nginx"
